---
- hosts: webservers
  tasks:
  - name: Loome allalaadimiseks kataloog
    file:
      path=/root/allalaadimised
      owner=root
      group=root
      mode=0755
      state=directory

  - name: Allalaadime mysql_5.7 repositooriumi pakett apt-i lisamiseks
    get_url:
      url: http://repo.mysql.com/mysql-apt-config_0.8.5-1_all.deb
      dest: "/root/allalaadimised"
      mode: 0440

  - name: installeerime mysql_5.7 repositoorium
    apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.5-1_all.deb"

  - name: installeerime mysql_5.7
    apt: name=mysql-server update_cache=yes state=present



  - name: installeerime python-mysqldb
    apt: name=python-mysqldb update_cache=yes state=latest

  - name: Loome kasutaja 'root' ja maarame talle parooliks 'qwerty' koos korgeimate privileegidega
    mysql_user:
      name: root
      password: qwerty
      priv: '*.*:ALL,GRANT'
      state: present

  - name: loome root login faili
    copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
          [client]
          user=root
          password=qwerty

  - name: alglaadimine mysql
    service: name=mysql state=restarted

