---
- hosts: webservers
  tasks:
    - name: php7.0 installeerimine
      apt: name=php7.0 update_cache=yes state=latest
    - name: libapache-mod-php7.0 installeerimine
      apt: name=libapache2-mod-php7.0 update_cache=yes state=latest
    - name: php7.0-mysql installeerimine
      apt: name=php7.0-mysql update_cache=yes state=latest
