---
- hosts: webservers
  tasks:

  - name: Loome andmebaasi wordpressi jaoks
    mysql_db:
      name: wpdatabase
      state: present
  - name: Loome kasutaja 'wpuser' parooliks 'qwerty' max privileegid
    mysql_user:
      name: wpuser
      password: qwerty
      priv: 'wpdatabase.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes
  - name: alglaadimine mysql
    service: name=mysql state=restarted
  
  - name: Laadime alla ja pakime lahti 
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Vahetame wordpressi kausta omaniku
    file:
      path: /var/www/html/wordpress/
      state: directory
      recurse: yes
      owner: www-data

  - name: conf faili ymbernimetamine
    command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

  - name: vahetame 'DB_PASSWORD'
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="password_here" line="define( 'DB_PASSWORD', 'qwerty' );"
  - name: vahetame 'DB_USER'
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="username_here" line="define( 'DB_USER', 'wpuser' );"
  - name: vahetame 'DB_NAME'
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="database_name_here" line="define( 'DB_NAME', 'wpdatabase' );"

